import activateSidebar from '../lib/activate-sidebar.js';

import aceEditor from '../lib/ace-editor.js';

import createGenericObject from './code-snippets/create-generic-object.js';
import createQListObjectDef from './code-snippets/create-q-list-object-def.js';
import qListObjectResponse from './code-snippets/q-list-object-response.js';
import listObjectQType from './code-snippets/list-object-q-type.js';
import requireListObject from './code-snippets/require-list-object.js';
import createSessionObject from './code-snippets/create-session-object.js';
import addQDef from './code-snippets/add-q-def.js';
import defineQInitialDataFetch from './code-snippets/define-q-initial-data-fetch.js';
import listboxInitialDataFetch from './code-snippets/listbox-initial-data-fetch.js';
import addQInitialDataFetch from './code-snippets/add-q-initial-data-fetch.js';
import listboxGetLayout from './code-snippets/listbox-get-layout.js';
import onInvalidation from './code-snippets/on-invalidation.js';
import listBoxHtml from './code-snippets/listbox-html.js';
import initializeRenderFilter from './code-snippets/initialize-render-filter.js';
import printListItems from './code-snippets/print-list-items.js';
import requireRenderFilter from './code-snippets/require-render-filter.js';
import callRenderFilter from './code-snippets/call-render-filter.js';
import listboxStyle from './code-snippets/listbox-style.js';
import selectListObjectValues from './code-snippets/select-list-object-values.js';
import passGenericObject from './code-snippets/pass-generic-object.js';
import createStateFilter from './code-snippets/create-state-filter.js';
import requireStateFilter from './code-snippets/require-state-filter.js';
import finalIndex from './code-snippets/final-index.js';

activateSidebar(7);

aceEditor('create-generic-object', 'json', createGenericObject, 'Generic Object Properties');
aceEditor('create-q-list-object-def', 'json', createQListObjectDef, 'Generic Object Properties');
aceEditor('q-list-object-response', 'json', qListObjectResponse, 'Generic Object Layout');
aceEditor('list-object-q-type', 'json', listObjectQType, 'src/defs/region-listobject.json');
aceEditor('require-list-object', 'javascript', requireListObject, 'src/index.js');
aceEditor('create-session-object', 'javascript', createSessionObject, 'src/index.js');
aceEditor('add-q-def', 'json', addQDef, 'src/defs/region-listobject.json');
aceEditor('define-q-initial-data-fetch', 'json', defineQInitialDataFetch, 'Initial Data Fetch');
aceEditor('listbox-initial-data-fetch', 'json', listboxInitialDataFetch, 'src/defs/region-listobject.json');
aceEditor('add-q-initial-data-fetch', 'json', addQInitialDataFetch, 'src/defs/region-listobject.json');
aceEditor('on-invalidation', 'javascript', onInvalidation, 'src/index.js');
aceEditor('listbox-html', 'html', listBoxHtml, 'dist/index.html');
aceEditor('initialize-render-filter', 'javascript', initializeRenderFilter, 'src/render-filter.js');
aceEditor('print-list-items', 'javascript', printListItems, 'src/render-filter.js');
aceEditor('require-render-filter', 'javascript', requireRenderFilter, 'src/index.js');
aceEditor('call-render-filter', 'javascript', callRenderFilter, 'src/index.js');
aceEditor('listbox-style', 'css', listboxStyle, 'dist/style.css');
aceEditor('select-list-object-values', 'javascript', selectListObjectValues, 'src/render-filter.js');
aceEditor('pass-generic-object', 'javascript', passGenericObject, 'src/index.js');
aceEditor('create-state-filter', 'json', createStateFilter, 'src/defs/state-listobject.json');
aceEditor('require-state-filter', 'javascript', requireStateFilter, 'src/defs/require-listobject.js');
aceEditor('final-index', 'javascript', finalIndex, 'src/index.js');
